# Generated by Django 3.2.7 on 2021-09-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog/image', verbose_name='Изображение статьи'),
        ),
    ]
