# Generated by Django 3.2.7 on 2021-09-26 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210926_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 26, 6, 29, 59, 512040, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
    ]
