# Generated by Django 3.2.7 on 2021-09-28 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 28, 14, 34, 55, 724366, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
    ]
